version: 2.0
jobs:
  build:
    working_directory: ~/Jandi
    docker:
      - image: circleci/php:7.1-apache-stretch-node-browsers
        environment:
          # Define these information to be used later in script
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: circleci
          DB_USERNAME: root
          DB_PASSWORD: ''
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci

    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Install things we need
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev
            sudo apt-get install -y zlib1g-dev libicu-dev g++
            sudo apt-get install mysql-client
            # sudo apt-get -y install mysql-server
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-configure intl
            sudo docker-php-ext-install intl
            sudo docker-php-ext-install pdo_mysql
      # - run:
      #     name: Fix MySQL socket config
      #     command: |
      #       sudo sh -c "echo 'pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock' > /usr/local/etc/php/conf.d/pdo.ini"

      - run:
         name: Download NodeJS v6
         command: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

      #sqlite needed for laravel database
      #nodejs6 needed to run `npm run watch` later
      - run:
         name: Install nodejs 6
         command: sudo apt-get install -y nodejs

      - run:
         name: Setup Laravel testing environment variables for CircleCI test
         command: cp .env.dusk.testing .env

      - run:
         name: Update composer to latest version
         command: sudo composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NodeJS Packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
         name: Migrate Laravel Database
         command: php artisan migrate --env=testing --force

      - run:
         name: Compile Javascript & CSS for Browser Testing
         command: npm run production

      # Neet to fix
      # - run:
      #    name: install dusk
      #    command: php artisan dusk:install

      - run:
         name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
         command: vendor/bin/phpunit

      # Neet to fix
      # - run:
      #    name: Test 2 - Run Laravel Desk for Browser Testing
      #    command: php artisan dusk